# Generated by Django 2.2.3 on 2019-07-22 17:52

from django.db import migrations

def add_categories(apps, schema_editor):
    from favorit_things_app.models import Category
    category = Category(name='person', description='person category')
    category.save()
    category = Category(name='place', description='place category')
    category.save()
    category = Category(name='food', description='food category')
    category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('favorit_things_app', '0002_auto_20190722_1740'),
    ]

    operations = [
            migrations.RunPython(add_categories),
    ]
